name: Maven Test, Build and Docker Push

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Echo Command
        run: echo Hello

      - name: Java Version
        run: java --version
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "20"

      - name: Java Version
        run: java --version
        
      - name: Maven Version
        run: mvn --version        
        
      # - name: Run Maven tests
      #   run: mvn test

  build:
    runs-on: ubuntu-latest
    needs: test   # only run if tests pass
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build with Maven
        run: mvn clean install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

